/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author JuWoj8013
 */
public class MakingPurchases extends javax.swing.JFrame {

    /**
     * Creates new form MakingPurchases
     */
    public MakingPurchases() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jPanel1 = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        subtitleLabel = new javax.swing.JLabel();
        chocolateLabel = new javax.swing.JLabel();
        vanillaLabel = new javax.swing.JLabel();
        redLabel = new javax.swing.JLabel();
        lemonLabel = new javax.swing.JLabel();
        chocolateText = new javax.swing.JTextField();
        vanillaText = new javax.swing.JTextField();
        redText = new javax.swing.JTextField();
        lemonText = new javax.swing.JTextField();
        calculateButton = new javax.swing.JButton();
        taxLabel = new javax.swing.JLabel();
        subtotalLabel = new javax.swing.JLabel();
        grandtotalLabel = new javax.swing.JLabel();
        taxLabel2 = new javax.swing.JLabel();
        subtotalLabel2 = new javax.swing.JLabel();
        grandtotalLabel2 = new javax.swing.JLabel();

        jToolBar1.setRollover(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        titleLabel.setFont(new java.awt.Font("A.C.M.E. Secret Agent", 0, 36)); // NOI18N
        titleLabel.setText("Cupcakes");

        subtitleLabel.setFont(new java.awt.Font("A.C.M.E. Secret Agent", 0, 10)); // NOI18N
        subtitleLabel.setText("Select the amount of each type \nof cupcake you wish to purchase");

        chocolateLabel.setFont(new java.awt.Font("A.C.M.E. Secret Agent", 0, 11)); // NOI18N
        chocolateLabel.setText("Chocolate (1.99$):");

        vanillaLabel.setFont(new java.awt.Font("A.C.M.E. Secret Agent", 0, 11)); // NOI18N
        vanillaLabel.setText("Vanilla (1.59$):");

        redLabel.setFont(new java.awt.Font("A.C.M.E. Secret Agent", 0, 11)); // NOI18N
        redLabel.setText("Red Velvet (2.50$):");

        lemonLabel.setFont(new java.awt.Font("A.C.M.E. Secret Agent", 0, 11)); // NOI18N
        lemonLabel.setText("Lemon (1.99$):");

        calculateButton.setText("Calculate");
        calculateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateButtonActionPerformed(evt);
            }
        });

        taxLabel.setFont(new java.awt.Font("A.C.M.E. Secret Agent", 0, 11)); // NOI18N
        taxLabel.setText("Taxes (13%):");

        subtotalLabel.setFont(new java.awt.Font("A.C.M.E. Secret Agent", 0, 11)); // NOI18N
        subtotalLabel.setText("Subtotal:");

        grandtotalLabel.setFont(new java.awt.Font("A.C.M.E. Secret Agent", 0, 11)); // NOI18N
        grandtotalLabel.setText("Grand Total:");

        taxLabel2.setFont(new java.awt.Font("A.C.M.E. Secret Agent", 0, 11)); // NOI18N
        taxLabel2.setText("0.00$");

        subtotalLabel2.setFont(new java.awt.Font("A.C.M.E. Secret Agent", 0, 11)); // NOI18N
        subtotalLabel2.setText("0.00$");

        grandtotalLabel2.setFont(new java.awt.Font("A.C.M.E. Secret Agent", 0, 11)); // NOI18N
        grandtotalLabel2.setText("0.00$");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lemonLabel)
                        .addGap(34, 34, 34)
                        .addComponent(lemonText, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chocolateLabel)
                            .addComponent(vanillaLabel)
                            .addComponent(redLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(chocolateText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(calculateButton))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(vanillaText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(redText, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(99, 99, 99)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(taxLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                                        .addComponent(taxLabel2)
                                        .addGap(0, 22, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(subtotalLabel)
                                            .addComponent(grandtotalLabel))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(grandtotalLabel2)
                                            .addComponent(subtotalLabel2))
                                        .addGap(11, 11, 11)))))))
                .addGap(68, 68, 68))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(subtitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subtitleLabel)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chocolateLabel)
                    .addComponent(chocolateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(calculateButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vanillaLabel)
                            .addComponent(vanillaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(redLabel)
                            .addComponent(redText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lemonLabel)
                            .addComponent(lemonText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(taxLabel)
                            .addComponent(taxLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(subtotalLabel)
                            .addComponent(subtotalLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(grandtotalLabel)
                            .addComponent(grandtotalLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calculateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateButtonActionPerformed
        double cTotalPrice = 0.0;
        double vTotalPrice = 0.0;
        double rTotalPrice = 0.0;
        double lTotalPrice = 0.0;
        double tax = 0.13;
        double subtotal = 0.0;
        double grandtotal = 0.0;
        double cNumber;
        cNumber = Double.parseDouble(chocolateText.getText());
        double vNumber;
        vNumber = Double.parseDouble(vanillaText.getText());
        double rNumber;
        rNumber = Double.parseDouble(redText.getText());
        double lNumber;
        lNumber = Double.parseDouble(lemonText.getText());
        cTotalPrice = (cNumber*1.99);
        vTotalPrice = (vNumber*1.59);
        rTotalPrice = (rNumber*2.50);
        lTotalPrice = (lNumber*1.99);
        subtotal = (cTotalPrice + vTotalPrice + rTotalPrice + lTotalPrice);
        grandtotal = (subtotal*1.13);
        subtotalLabel2.setText("$ " +subtotal);
        taxLabel2.setText("$ "+subtotal*tax);
        grandtotalLabel2.setText("$ "+grandtotal);
    }//GEN-LAST:event_calculateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MakingPurchases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MakingPurchases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MakingPurchases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MakingPurchases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MakingPurchases().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculateButton;
    private javax.swing.JLabel chocolateLabel;
    private javax.swing.JTextField chocolateText;
    private javax.swing.JLabel grandtotalLabel;
    private javax.swing.JLabel grandtotalLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lemonLabel;
    private javax.swing.JTextField lemonText;
    private javax.swing.JLabel redLabel;
    private javax.swing.JTextField redText;
    private javax.swing.JLabel subtitleLabel;
    private javax.swing.JLabel subtotalLabel;
    private javax.swing.JLabel subtotalLabel2;
    private javax.swing.JLabel taxLabel;
    private javax.swing.JLabel taxLabel2;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel vanillaLabel;
    private javax.swing.JTextField vanillaText;
    // End of variables declaration//GEN-END:variables
}
